#!/bin/bash

if [ "$BLOCK_BUTTON" -eq 1 ]; then
    selected=$(echo -e 'Shutdown\nReboot\nLogout\nSuspend' | rofi -dmenu -p 'Power')
    case $selected in
        "Shutdown") poweroff ;;
        "Reboot") reboot ;;
        "Logout") i3-msg exit ;;
        "Suspend") systemctl suspend ;;
    esac
fi
